title: CJKwrap
description: CJKwrap is a library for wrapping and filling CJK text. Fix Python issue24665.
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
